"""Add generation_status to project assets

Revision ID: 0190deac851d
Revises: 5be541bbe693
Create Date: 2026-02-07 17:56:28.650125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0190deac851d'
down_revision = '5be541bbe693'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_assets', sa.Column('generation_status', sa.Enum('PENDING', 'GENERATING', 'COMPLETE', 'FAILED', name='assetstatus'), nullable=False))
    op.alter_column('project_assets', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('project_assets', 'file_format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_assets', 'file_format',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project_assets', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('project_assets', 'generation_status')
    # ### end Alembic commands ###
