"""Add project_id to project_ideas

Revision ID: 17baf679bb5c
Revises: 4ea641d42780
Create Date: 2026-02-07 13:11:26.919413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17baf679bb5c'
down_revision = '4ea641d42780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_ideas', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'project_ideas', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_ideas', type_='foreignkey')
    op.drop_column('project_ideas', 'project_id')
    # ### end Alembic commands ###
