"""Restructure_hierarchy

Revision ID: 1b116f5e0adf
Revises: 4a5b6c7d8e9f
Create Date: 2026-01-27 03:41:30.033566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b116f5e0adf'
down_revision = '4a5b6c7d8e9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'issues', 'issues', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('milestones_parent_id_fkey'), 'milestones', type_='foreignkey')
    op.drop_column('milestones', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('milestones_parent_id_fkey'), 'milestones', 'milestones', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'parent_id')
    # ### end Alembic commands ###
