"""Add issue_type to Issue

Revision ID: 1f3fb903b17e
Revises: 8e25dcdd6125
Create Date: 2026-01-26 17:34:13.505723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3fb903b17e'
down_revision = '8e25dcdd6125'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('issue_type', sa.Enum('BUG', 'TASK', 'REFACTOR', 'CHORE', 'TECH_DEBT', 'INVESTIGATION', name='issuetype'), nullable=False, server_default='TASK'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'issue_type')
    # ### end Alembic commands ###
