"""add priority to feature

Revision ID: 234399c000c1
Revises: f1a2b3c4d5e6
Create Date: 2026-01-27 00:36:33.875422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234399c000c1'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('features', sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', 'NONE', name='issuepriority'), nullable=True))
    
    # Update existing rows to 'NONE'
    op.execute("UPDATE features SET priority = 'NONE'")
    
    # Set nullable to False
    op.alter_column('features', 'priority', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'priority')
    # ### end Alembic commands ###
