"""link_idea_to_project

Revision ID: 234ecbf46c89
Revises: efa4d48c2f98
Create Date: 2026-02-09 15:46:36.533612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234ecbf46c89'
down_revision = 'efa4d48c2f98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_ideas', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'project_ideas', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_ideas', type_='foreignkey')
    op.drop_column('project_ideas', 'project_id')
    # ### end Alembic commands ###
