"""add type_changed to activitytype

Revision ID: 2c5f5b3dac36
Revises: 1f3fb903b17e
Create Date: 2026-01-26 18:09:29.013851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5f5b3dac36'
down_revision = '1f3fb903b17e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'milestones', 'milestones', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    
    # Manual update for ActivityType enum
    op.execute("ALTER TYPE activitytype ADD VALUE 'type_changed'")


def downgrade() -> None:
    # Downgrading enums is difficult in Postgres as it doesn't support DROP VALUE
    # Usually we leave it as is or recreate the type
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.drop_column('milestones', 'parent_id')
    # ### end Alembic commands ###
