"""Sync final state

Revision ID: 4ea641d42780
Revises: a4c027dfc63a
Create Date: 2026-02-07 12:27:37.526464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea641d42780'
down_revision = 'a4c027dfc63a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
