"""Update IdeaStatus enum values

Revision ID: 5be541bbe693
Revises: 17baf679bb5c
Create Date: 2026-02-07 17:03:22.631650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be541bbe693'
down_revision = '17baf679bb5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ideastatus ADD VALUE 'VALIDATING'")
    op.execute("ALTER TYPE ideastatus ADD VALUE 'GENERATING_ASSETS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
