"""Refactor team leaders and project team constraint

Revision ID: 8e25dcdd6125
Revises: e888a25fa007
Create Date: 2026-01-26 05:21:59.502917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e25dcdd6125'
down_revision = 'e888a25fa007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'team_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('projects_team_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teams_leader_id_fkey'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'leader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('leader_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('teams_leader_id_fkey'), 'teams', 'users', ['leader_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_team_id_fkey'), 'projects', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'team_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
