"""initial_schema_v2_project_feature_issue

Revision ID: 9eb72b462028
Revises: 
Create Date: 2026-01-25 23:15:40.493817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb72b462028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'feature_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('issues_project_id_fkey'), 'issues', type_='foreignkey')
    op.drop_constraint(op.f('issues_feature_id_fkey'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'features', ['feature_id'], ['id'], ondelete='CASCADE')
    op.drop_column('issues', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_feature_id_fkey'), 'issues', 'features', ['feature_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('issues_project_id_fkey'), 'issues', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.alter_column('issues', 'feature_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
