"""Add project_ideas, validation_reports, project_assets tables

Revision ID: a4c027dfc63a
Revises: a40dc2aa1f77
Create Date: 2026-02-07 12:23:05.159352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4c027dfc63a'
down_revision = 'a40dc2aa1f77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_dependencies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_dependencies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feature_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('depends_on_feature_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['depends_on_feature_id'], ['features.id'], name=op.f('feature_dependencies_depends_on_feature_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('feature_dependencies_feature_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feature_dependencies_pkey'))
    )
    # ### end Alembic commands ###
