"""initial schema

Revision ID: a73a1678dc33
Revises:
Create Date: 2026-02-24 19:31:10.114598

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a73a1678dc33"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users first (no FK to organizations yet)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_index(
        "idx_users_organization_id", "users", ["organization_id"], unique=False
    )
    op.create_index("ix_users_email", "users", ["email"], unique=False)

    # Create organizations (with FK to users)
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_organizations_name", "organizations", ["name"], unique=False)
    op.create_table(
        "resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("PROJECT", "ISSUE", name="resourcetargettype"),
            nullable=False,
        ),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column(
            "type", sa.Enum("LINK", "DOCUMENT", name="resourcetype"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_resources_target", "resources", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "invite_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_invite_codes_organization_id",
        "invite_codes",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_invite_codes_code"), "invite_codes", ["code"], unique=True)
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "ISSUE_ASSIGNED",
                "ISSUE_STATUS_CHANGED",
                "ISSUE_COMMENT",
                "ISSUE_MENTION",
                "ISSUE_PRIORITY_UPGRADE",
                "AI_VALIDATION_READY",
                "AI_BLUEPRINT_READY",
                "AI_DOC_GENERATED",
                "AI_ISSUES_CREATED",
                "TEAM_INVITE",
                "TEAM_MEMBER_JOINED",
                "ORG_ROLE_CHANGED",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.String(), nullable=True),
        sa.Column("target_type", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notifications_is_read", "notifications", ["is_read"], unique=False
    )
    op.create_index(
        "idx_notifications_recipient_id",
        "notifications",
        ["recipient_id"],
        unique=False,
    )
    op.create_table(
        "reactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "PROJECT_UPDATE", "PROJECT_UPDATE_COMMENT", name="reactiontargettype"
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("emoji", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_reactions_target", "reactions", ["target_type", "target_id"], unique=False
    )
    op.create_index("idx_reactions_user_id", "reactions", ["user_id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("identifier", sa.String(length=5), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "identifier", name="unique_org_team_identifier"
        ),
    )
    op.create_index(
        "idx_teams_organization_id", "teams", ["organization_id"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "LEADER", "MEMBER", name="userroletype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "organization_id", name="unique_user_org"),
    )
    op.create_index(
        "idx_user_roles_organization_id",
        "user_roles",
        ["organization_id"],
        unique=False,
    )
    op.create_index("idx_user_roles_user_id", "user_roles", ["user_id"], unique=False)
    op.create_table(
        "views",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column(
            "type", sa.Enum("ISSUES", "PROJECTS", name="viewtype"), nullable=False
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("PERSONAL", "TEAM", name="viewvisibility"),
            nullable=False,
        ),
        sa.Column("filter_config", sa.JSON(), nullable=False),
        sa.Column(
            "layout", sa.Enum("LIST", "BOARD", name="viewlayout"), nullable=False
        ),
        sa.Column("view_subtype", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_views_owner_id", "views", ["owner_id"], unique=False)
    op.create_index("idx_views_type", "views", ["type"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "BACKLOG",
                "PLANNED",
                "IN_PROGRESS",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                name="projectstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "health",
            sa.Enum(
                "ON_TRACK", "AT_RISK", "OFF_TRACK", "NO_UPDATES", name="projecthealth"
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("URGENT", "HIGH", "MEDIUM", "LOW", "NONE", name="projectpriority"),
            nullable=False,
        ),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("TEAM", "ORGANIZATION", name="visibility"),
            nullable=False,
        ),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_projects_created_at", "projects", ["created_at"], unique=False)
    op.create_index("idx_projects_health", "projects", ["health"], unique=False)
    op.create_index("idx_projects_status", "projects", ["status"], unique=False)
    op.create_index("idx_projects_team_id", "projects", ["team_id"], unique=False)
    op.create_table(
        "team_leaders",
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("team_id", "user_id", name="unique_team_member"),
    )
    op.create_table(
        "features",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("identifier", sa.String(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("blueprint_node_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=True),
        sa.Column("target_user", sa.String(), nullable=True),
        sa.Column("expected_outcome", sa.Text(), nullable=True),
        sa.Column("success_metric", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "NEW_CAPABILITY",
                "ENHANCEMENT",
                "EXPERIMENT",
                "INFRASTRUCTURE",
                name="featuretype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DISCOVERY",
                "VALIDATED",
                "IN_BUILD",
                "IN_REVIEW",
                "SHIPPED",
                "ADOPTED",
                "KILLED",
                name="featurestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("URGENT", "HIGH", "MEDIUM", "LOW", "NONE", name="issuepriority"),
            nullable=False,
        ),
        sa.Column("validation_evidence", sa.Text(), nullable=True),
        sa.Column(
            "health",
            sa.Enum("ON_TRACK", "AT_RISK", "OFF_TRACK", name="featurehealth"),
            nullable=False,
        ),
        sa.Column("delivery_confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["features.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_features_project_id", "features", ["project_id"], unique=False)
    op.create_index("idx_features_status", "features", ["status"], unique=False)
    op.create_index(
        op.f("ix_features_blueprint_node_id"),
        "features",
        ["blueprint_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_features_identifier"), "features", ["identifier"], unique=True
    )
    op.create_table(
        "project_ideas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("raw_input", sa.String(), nullable=False),
        sa.Column("refined_description", sa.String(), nullable=True),
        sa.Column("clarification_questions", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "CLARIFICATION_NEEDED",
                "READY_FOR_VALIDATION",
                "VALIDATED",
                "BLUEPRINT_GENERATED",
                "COMPLETED",
                name="ideastatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_project_ideas_status", "project_ideas", ["status"], unique=False
    )
    op.create_index(
        "idx_project_ideas_user_id", "project_ideas", ["user_id"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "project_teams",
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "project_updates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "health",
            sa.Enum(
                "ON_TRACK", "AT_RISK", "OFF_TRACK", "NO_UPDATES", name="projecthealth"
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_project_updates_created_at",
        "project_updates",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_project_updates_project_id",
        "project_updates",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_milestones_feature_id", "milestones", ["feature_id"], unique=False
    )
    op.create_table(
        "project_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_idea_id", sa.UUID(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum(
                "PROJECT_MD",
                "PRD",
                "APP_FLOW",
                "TECH_STACK",
                "FRONTEND_GUIDELINES",
                "BACKEND_SCHEMA",
                "IMPLEMENTATION_PLAN",
                "DIAGRAM_USER_FLOW",
                "DIAGRAM_KANBAN",
                name="assettype",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("r2_path", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "GENERATING", "COMPLETED", "FAILED", name="assetstatus"),
            nullable=False,
        ),
        sa.Column("chat_history", sa.JSON(), nullable=True),
        sa.Column("analysis_result", sa.JSON(), nullable=True),
        sa.Column("enhanced_content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_idea_id"], ["project_ideas.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_project_assets_project_idea_id",
        "project_assets",
        ["project_idea_id"],
        unique=False,
    )
    op.create_table(
        "project_update_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("update_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["project_update_comments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["update_id"], ["project_updates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_project_update_comments_update_id",
        "project_update_comments",
        ["update_id"],
        unique=False,
    )
    op.create_table(
        "validation_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_idea_id", sa.UUID(), nullable=False),
        sa.Column("market_feasibility", sa.JSON(), nullable=False),
        sa.Column("improvements", sa.JSON(), nullable=False),
        sa.Column("core_features", sa.JSON(), nullable=False),
        sa.Column("tech_stack", sa.JSON(), nullable=False),
        sa.Column("pricing_model", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_idea_id"], ["project_ideas.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "issue_type",
            sa.Enum(
                "BUG",
                "TASK",
                "REFACTOR",
                "CHORE",
                "TECH_DEBT",
                "INVESTIGATION",
                name="issuetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "BACKLOG",
                "TODO",
                "IN_PROGRESS",
                "DONE",
                "CANCELLED",
                name="issuestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("URGENT", "HIGH", "MEDIUM", "LOW", "NONE", name="issuepriority"),
            nullable=False,
        ),
        sa.Column(
            "triage_status",
            sa.Enum(
                "PENDING", "ACCEPTED", "DECLINED", "DUPLICATE", name="triagestatus"
            ),
            nullable=True,
        ),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("TEAM", "ORGANIZATION", name="visibility"),
            nullable=False,
        ),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.Column("milestone_id", sa.UUID(), nullable=True),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("blueprint_node_id", sa.String(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["milestone_id"], ["milestones.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_issues_assignee_id", "issues", ["assignee_id"], unique=False)
    op.create_index("idx_issues_feature_id", "issues", ["feature_id"], unique=False)
    op.create_index("idx_issues_identifier", "issues", ["identifier"], unique=False)
    op.create_index("idx_issues_status", "issues", ["status"], unique=False)
    op.create_index("idx_issues_team_id", "issues", ["team_id"], unique=False)
    op.create_index(
        op.f("ix_issues_blueprint_node_id"),
        "issues",
        ["blueprint_node_id"],
        unique=False,
    )
    op.create_index(op.f("ix_issues_identifier"), "issues", ["identifier"], unique=True)
    op.create_table(
        "activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "created",
                "status_changed",
                "priority_changed",
                "type_changed",
                "assigned",
                "comment",
                name="activitytype",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_activities_actor_id", "activities", ["actor_id"], unique=False)
    op.create_index(
        "idx_activities_created_at", "activities", ["created_at"], unique=False
    )
    op.create_index("idx_activities_issue_id", "activities", ["issue_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_comments_author_id", "comments", ["author_id"], unique=False)
    op.create_index("idx_comments_issue_id", "comments", ["issue_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_comments_issue_id", table_name="comments")
    op.drop_index("idx_comments_author_id", table_name="comments")
    op.drop_table("comments")
    op.drop_index("idx_activities_issue_id", table_name="activities")
    op.drop_index("idx_activities_created_at", table_name="activities")
    op.drop_index("idx_activities_actor_id", table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_issues_identifier"), table_name="issues")
    op.drop_index(op.f("ix_issues_blueprint_node_id"), table_name="issues")
    op.drop_index("idx_issues_team_id", table_name="issues")
    op.drop_index("idx_issues_status", table_name="issues")
    op.drop_index("idx_issues_identifier", table_name="issues")
    op.drop_index("idx_issues_feature_id", table_name="issues")
    op.drop_index("idx_issues_assignee_id", table_name="issues")
    op.drop_table("issues")
    op.drop_table("validation_reports")
    op.drop_index(
        "idx_project_update_comments_update_id", table_name="project_update_comments"
    )
    op.drop_table("project_update_comments")
    op.drop_index("idx_project_assets_project_idea_id", table_name="project_assets")
    op.drop_table("project_assets")
    op.drop_index("idx_milestones_feature_id", table_name="milestones")
    op.drop_table("milestones")
    op.drop_index("idx_project_updates_project_id", table_name="project_updates")
    op.drop_index("idx_project_updates_created_at", table_name="project_updates")
    op.drop_table("project_updates")
    op.drop_table("project_teams")
    op.drop_table("project_members")
    op.drop_index("idx_project_ideas_user_id", table_name="project_ideas")
    op.drop_index("idx_project_ideas_status", table_name="project_ideas")
    op.drop_table("project_ideas")
    op.drop_index(op.f("ix_features_identifier"), table_name="features")
    op.drop_index(op.f("ix_features_blueprint_node_id"), table_name="features")
    op.drop_index("idx_features_status", table_name="features")
    op.drop_index("idx_features_project_id", table_name="features")
    op.drop_table("features")
    op.drop_table("team_members")
    op.drop_table("team_leaders")
    op.drop_index("idx_projects_team_id", table_name="projects")
    op.drop_index("idx_projects_status", table_name="projects")
    op.drop_index("idx_projects_health", table_name="projects")
    op.drop_index("idx_projects_created_at", table_name="projects")
    op.drop_table("projects")
    op.drop_index("idx_views_type", table_name="views")
    op.drop_index("idx_views_owner_id", table_name="views")
    op.drop_table("views")
    op.drop_index("idx_user_roles_user_id", table_name="user_roles")
    op.drop_index("idx_user_roles_organization_id", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index("idx_teams_organization_id", table_name="teams")
    op.drop_table("teams")
    op.drop_index("idx_reactions_user_id", table_name="reactions")
    op.drop_index("idx_reactions_target", table_name="reactions")
    op.drop_table("reactions")
    op.drop_index("idx_notifications_recipient_id", table_name="notifications")
    op.drop_index("idx_notifications_is_read", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_invite_codes_code"), table_name="invite_codes")
    op.drop_index("idx_invite_codes_organization_id", table_name="invite_codes")
    op.drop_table("invite_codes")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("idx_users_organization_id", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_resources_target", table_name="resources")
    op.drop_table("resources")
    op.drop_index("idx_organizations_name", table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
