"""Add notifications table

Revision ID: c63051922288
Revises: f46ccb5f0a3d
Create Date: 2026-02-18 17:43:55.968458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63051922288'
down_revision = 'f46ccb5f0a3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
