"""add_pdf_docx_paths_to_assets

Revision ID: ced97914b4f7
Revises: 0190deac851d
Create Date: 2026-02-07 18:32:57.542221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced97914b4f7'
down_revision = '0190deac851d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_assets', sa.Column('storage_path_pdf', sa.String(), nullable=True))
    op.add_column('project_assets', sa.Column('storage_path_docx', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_assets', 'storage_path_docx')
    op.drop_column('project_assets', 'storage_path_pdf')
    # ### end Alembic commands ###
