"""add parent_id to feature

Revision ID: d4d9956c60f1
Revises: 234ecbf46c89
Create Date: 2026-02-14 08:37:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4d9956c60f1'
down_revision = '234ecbf46c89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_features_parent_id', 'features', 'features', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_features_parent_id', 'features', type_='foreignkey')
    op.drop_column('features', 'parent_id')
    # ### end Alembic commands ###
