"""add_doc_analysis_columns

Revision ID: e7fe059cfa14
Revises: c63051922288
Create Date: 2026-02-20 15:04:22.571620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fe059cfa14'
down_revision = 'c63051922288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_assets', sa.Column('analysis_result', sa.JSON(), nullable=True))
    op.add_column('project_assets', sa.Column('enhanced_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_assets', 'enhanced_content')
    op.drop_column('project_assets', 'analysis_result')
    # ### end Alembic commands ###
