"""Add is_favorite to Project

Revision ID: e888a25fa007
Revises: 9eb72b462028
Create Date: 2026-01-26 04:47:39.905335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e888a25fa007'
down_revision = '9eb72b462028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_favorite')
    # ### end Alembic commands ###
