"""add blueprint_node_id to issue and feature

Revision ID: f46ccb5f0a3d
Revises: d4d9956c60f1
Create Date: 2026-02-15 17:58:13.708354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46ccb5f0a3d'
down_revision = 'd4d9956c60f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('blueprint_node_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_features_blueprint_node_id'), 'features', ['blueprint_node_id'], unique=False)
    op.add_column('issues', sa.Column('blueprint_node_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_issues_blueprint_node_id'), 'issues', ['blueprint_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_blueprint_node_id'), table_name='issues')
    op.drop_column('issues', 'blueprint_node_id')
    op.drop_index(op.f('ix_features_blueprint_node_id'), table_name='features')
    op.drop_column('features', 'blueprint_node_id')
    # ### end Alembic commands ###
