"""upadate identifier to 3 char max

Revision ID: fdf4ab59a20e
Revises: a73a1678dc33
Create Date: 2026-02-25 00:00:31.815283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf4ab59a20e'
down_revision = 'a73a1678dc33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=3),
               existing_nullable=False)
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.create_foreign_key('fk_users_organization', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_organization', type_='foreignkey')
        batch_op.drop_index('ix_users_email')
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
